#lang racket
(display "Задание 1\n")
(display "Вычисление объема куба\n")
(display "Введите длину ребра(см) и нажмите клавижу Enter\n")
(define a(read))
(define (cube x)
  (*(* x x) x))
(display (format "Объем куба: ~a куб.см" (cube a)))

(display "\nЗадание 2\n")
(display "Вычисление объема цилиндра.\n")
(display "Введите исходные данные:\n")
(display "радиус основания (см)\n")
(define r(read))
(display "высота цилиндра (см)\n")
(define h(read))
(define pi 3.14)
(display (format "Объем цилиндра ~a см. куб." (*(* pi r)h)))

(display "\nЗадание 3\n")
(display "Вычисление стоимости покупки\n")
(display "Введите исходные данные:\n")
(display "Цена тетради (руб.)\n")
(define ct(read))
(display "Количество тетрадей\n")
(define kt(read))
(display "Цена карандаша (руб.)\n")
(define ck(read))
(display "Количество карандашей\n")
(define kk(read))
(display (format "Стоимость покупки ~a руб."(+ (* ct kt) (* ck kk))))
